version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=BBVA Credit Calculator API
      - VERSION=1.0.0
      - DESCRIPTION=API for BBVA Credit Pre-evaluation System
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - .:/app
      - /app/__pycache__
      - ./file_manager:/app/file_manager
      - ./resumen_manager:/app/resumen_manager
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s