[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
APP_NAME = "BBVA Credit Calculator API"
VERSION = "1.0.0" 
DESCRIPTION = "API for BBVA Credit Pre-evaluation System"
DEBUG = "false"
HOST = "0.0.0.0"
WORKERS = "2"
LOG_LEVEL = "info"
